version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: habit_tracker
      POSTGRES_USER: habit_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    networks:
      - app-network

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://habit_user:your_password@db:5432/habit_tracker
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - .:/app
    networks:
      - app-network

  celery:
    build: .
    command: celery -A config worker -l info
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://habit_user:your_password@db:5432/habit_tracker
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - .:/app
    networks:
      - app-network

  celery-beat:
    build: .
    command: celery -A config beat -l info
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://habit_user:your_password@db:5432/habit_tracker
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - .:/app
    networks:
      - app-network

  nginx:
    image: nginx:1.23
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
