# Generated by Django 5.1.7 on 2025-03-28 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100)),
                ("time", models.TimeField()),
                ("action", models.CharField(max_length=200)),
                ("is_pleasant", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Daily"),
                            (2, "Every 2 days"),
                            (3, "Every 3 days"),
                            (4, "Every 4 days"),
                            (5, "Every 5 days"),
                            (6, "Every 6 days"),
                            (7, "Weekly"),
                        ],
                        default=1,
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=200, null=True)),
                ("duration", models.PositiveIntegerField()),
                ("is_public", models.BooleanField(default=False)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
